--- #YAML:1.0
name:                Gtk2-Unique
version:             0.01
abstract:            Use single instance applications
license:             perl, lgpl
author:              
    - Emmanuel Rodriguez <potyl@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Gtk2:                          1.161
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
